apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: external-secrets-operator
spec:
    destination:
        namespace: argocd
        server: https://kubernetes.default.svc
    project: argocd
    source:
        chart: external-secrets
        repoURL: https://charts.external-secrets.io
        targetRevision: "v0.5.2"